# Generated by Django 3.2 on 2021-11-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211119_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='type',
            new_name='choice',
        ),
    ]
