# Generated by Django 3.2 on 2021-11-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_type_vote_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='author',
        ),
    ]
