# Generated by Django 3.2 on 2021-11-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_user_vote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=8),
        ),
    ]
