name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents to vps via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/projects/copypasty/app"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      working-directory: "/root/projects/copypasty"
      run: cd /root/projects/copypasty & ls & source copypastyenv/bin/activate & cd app & pip install -r requirements.txt
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        PASSWORD: ${{ secrets.SSHKEY }}
        script: sudo systemctl restart django_one.socket & sudo systemctl restart django_one.service